language: node_js
node_js:
  - 10

cache: npm

before_install:
  - sed -i 's/ssh:\/\/git@/https:\/\//g' package-lock.json

before_script:
  - "echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p"

script:
  - npm run build
  - npm test
